name: "Shared steps for package publish"
description: "Common steps fto publish package"

inputs:
  working-directory:
    description: "The directory where the action should run."
    required: true

outputs:
  current-version:
    description: "The current npm version."

runs:
  using: "composite"

  steps: 
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        registry-url: https://registry.npmjs.org

    - name: Publish Shared Components to npm
      shell: bash 
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_WORKFLOW }}
