name: path

on:
  push:
    branches:
      - main

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      ssBtn: ${{ steps.filter.outputs.ssBtn }}
      ssHeader: ${{ steps.filter.outputs.ssHeader }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check for changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            ssBtn:
              - 'package/ss-button/**'
            ssHeader:
              - 'package/ss-header/**'

  ssBtn:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.ssBtn == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Go to Package Directory
        run: cd package/ss-button && pwd

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org

      - name: Get npm version
        id: npm-tag
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: package/ss-button

      - name: Install Dependencies
        run: npm cache clean --force && npm install

      - name: Build Library
        run: npm run build

      - name: Publish Shared Components to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_WORKFLOW }}

      - name: Create git tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: v${{ steps.npm-tag.outputs.current-version }}

  ssHeader:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.ssHeader == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Go to Package Directory
        run: cd package/ss-header && pwd

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org

      - name: Get npm version
        id: npm-tag
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: package/ss-header

      - name: Install Dependencies
        run: npm cache clean --force && npm install

      - name: Build Library
        run: npm run build

      - name: Publish Shared Components to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_WORKFLOW }}

      - name: Create git tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: v${{ steps.npm-tag.outputs.current-version }}
