name: "Shared steps for package publish"

defaults:
  run:
    shell: bash

on:
  workflow_call:
    inputs:
      working-directory:
        description: "The directory where the action should run."
        required: true
        type: string


jobs:
  setup-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Publish Shared Components to npm
        run: |
          cd ${{ inputs.working-directory }}
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_WORKFLOW }}
