name: "Shared steps for package publish"

defaults:
  run:
    shell: bash

on:
  workflow_call:
    inputs:
      working-directory:
        description: "The directory where the action should run."
        required: true
        type: string

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: ${{ inputs.working-directory }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org

      - name: Publish Shared Components to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_WORKFLOW }}
